/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DLProdutos.java
 *
 * Created on 14/06/2010, 15:38:22
 */

package View_consulta;

import classess.Utilitario;
import Views.FMaster;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Maicol
 */
public class DLFornecedor extends javax.swing.JDialog {
    JTextField tfcod_fornecedor;
    /** Creates new form DLProdutos */
    public DLFornecedor(java.awt.Frame parent, boolean modal, JTextField tfcod_fornecedor) {
        super(parent, modal);        
        initComponents();
        //redimenciona o lookandFeeld de acordo com o selecionado
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        this.tfcod_fornecedor = tfcod_fornecedor;
        PreencherJtable();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBFornecedor = new javax.swing.JTable();
        TFConsultaFornecedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de produtos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        TBFornecedor.setAutoCreateRowSorter(true);
        TBFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cód. Fornecedor", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBFornecedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TBFornecedor.setSelectionBackground(new java.awt.Color(0, 204, 204));
        TBFornecedor.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TBFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBFornecedorMouseClicked(evt);
            }
        });
        TBFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TBFornecedorKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TBFornecedor);
        TBFornecedor.getColumnModel().getColumn(0).setMinWidth(5);
        TBFornecedor.getColumnModel().getColumn(0).setPreferredWidth(5);

        TFConsultaFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFConsultaFornecedorFocusLost(evt);
            }
        });
        TFConsultaFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFConsultaFornecedorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TFConsultaFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TFConsultaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-657)/2, (screenSize.height-405)/2, 657, 405);
    }// </editor-fold>//GEN-END:initComponents

    private void TBFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBFornecedorMouseClicked
        if ( evt.getClickCount() > 1) {
            tfcod_fornecedor.setText(Utilitario.getValueColumn("Cód. Fornecedor", TBFornecedor));
            dispose();
        }
    }//GEN-LAST:event_TBFornecedorMouseClicked

    private void TBFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBFornecedorKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
           tfcod_fornecedor.setText(Utilitario.getValueColumn("Cód. Fornecedor", TBFornecedor));
           dispose();
        }
    }//GEN-LAST:event_TBFornecedorKeyPressed

    private void TFConsultaFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFConsultaFornecedorFocusLost
       if (!TFConsultaFornecedor.getText().isEmpty()) PreencherJtable();
       if (TBFornecedor.getRowCount() > 0) {
           TBFornecedor.requestFocus();
           TBFornecedor.setRowSelectionInterval(0, 0) ;
       }
    }//GEN-LAST:event_TFConsultaFornecedorFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void TFConsultaFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFConsultaFornecedorKeyReleased
        PreencherJtable();
    }//GEN-LAST:event_TFConsultaFornecedorKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBFornecedor;
    private javax.swing.JTextField TFConsultaFornecedor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

 private void PreencherJtable() {
     ResultSet rsProduto;
        if (TFConsultaFornecedor.getText().isEmpty()) {
            rsProduto = FMaster.con.executeSQL("select * from estfornecedor");
        } else {
            rsProduto = FMaster.con.executeSQL("select * from estfornecedor  where UPPER(nome) like UPPER('%" + TFConsultaFornecedor.getText() + "%')");
        }
        DefaultTableModel modelo = (DefaultTableModel) TBFornecedor.getModel();
        modelo.setNumRows(0);
        try {
            rsProduto.first();
            if (rsProduto.isFirst()) {
                do {                    
                    modelo.addRow(new Object[]{rsProduto.getInt("id_fornecedor"), rsProduto.getString("nome")});
                } while (rsProduto.next());
            }
            rsProduto.close();
        } catch (SQLException ex) {
            Logger.getLogger(DLProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
