/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DLCadItemEntrada.java
 *
 * Created on 08/12/2010, 20:46:17
 */
package Views;

import classess.Utilitario;
import View_consulta.DLInsumos;
import View_consulta.DLProdutos;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Demir
 */
public class DLCadItemEntrada extends javax.swing.JDialog {

    int id_entrada = 0;
    int id_itementrada = 0;
    int id_produto = 0;
    int status = 0;
    IFEntradaProdutos frameEntradaProduto;

    /** Creates new form DLCadItemEntrada */
    public DLCadItemEntrada(java.awt.Frame parent, boolean modal, int id_itementrada, int id_entrada, int id_produto, int status, IFEntradaProdutos frameEntradaProduto) {
        super(parent, modal);
        initComponents();
        //redimenciona o lookandFeeld de acordo com o selecionado
//        SwingUtilities.updateComponentTreeUI(this);
//        this.pack();
        this.id_itementrada = id_itementrada;
        this.id_entrada = id_entrada;
        this.id_produto = id_produto;
        this.status = status;
        this.frameEntradaProduto = frameEntradaProduto;

        if (status == 2) {
            PreencheDadosTela();
        }



        TFCodProduto.setInputVerifier(new InputVerifier() {

            @Override
            public boolean verify(JComponent input) {
                JTextField texto = (JTextField) input;
                boolean valida = false;
                if (!texto.getText().isEmpty()) {
                    try {
                        ResultSet rsproduto = FMaster.con.executeSQL("select * from estproduto where id_produto = '" + texto.getText() + "'");
                        rsproduto.first();
                        if (rsproduto.isFirst()) {
                            valida = true;
                        } else {
                            JOptionPane.showMessageDialog(null, "Produto não cadastrado!", "Alerta", JOptionPane.ERROR_MESSAGE);
                            valida = false;
                        }
                        rsproduto.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(DLCadProdComanda.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    valida = true;
                }
                return valida;
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTSalvar = new javax.swing.JButton();
        BTFechar = new javax.swing.JButton();
        TFCodProduto = new Componentes.DKJTFInteger();
        TFDescricaoProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFVlrUnitario = new Componentes.DKJTFFloat();
        jLabel5 = new javax.swing.JLabel();
        TFValorTotal = new Componentes.DKJTFFloat();
        jLabel6 = new javax.swing.JLabel();
        TFUnidade = new javax.swing.JTextField();
        TFQuantidade = new Componentes.DKJTFFloat3Casas();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastra e Altera produto da entrada");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        BTSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save_16.png"))); // NOI18N
        BTSalvar.setText("Salvar");
        BTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BTSalvar);
        BTSalvar.setBounds(210, 110, 92, 25);

        BTFechar.setText("Sair");
        BTFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFecharActionPerformed(evt);
            }
        });
        BTFechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BTFecharKeyPressed(evt);
            }
        });
        jPanel1.add(BTFechar);
        BTFechar.setBounds(310, 110, 77, 24);

        TFCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCodProdutoActionPerformed(evt);
            }
        });
        TFCodProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFCodProdutoFocusLost(evt);
            }
        });
        TFCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFCodProdutoKeyPressed(evt);
            }
        });
        jPanel1.add(TFCodProduto);
        TFCodProduto.setBounds(10, 30, 80, 20);

        TFDescricaoProduto.setEditable(false);
        TFDescricaoProduto.setFocusable(false);
        jPanel1.add(TFDescricaoProduto);
        TFDescricaoProduto.setBounds(120, 30, 270, 20);

        jLabel1.setText("Cód. produto(F1)");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 14);

        jLabel2.setText("Descrição do produto");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 10, 200, 14);

        jLabel3.setText("Unidade");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 76, 14);

        jLabel4.setText("Quantidade");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 60, 76, 14);

        TFVlrUnitario.setText("");
        TFVlrUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFVlrUnitarioFocusLost(evt);
            }
        });
        jPanel1.add(TFVlrUnitario);
        TFVlrUnitario.setBounds(210, 80, 83, 20);

        jLabel5.setText("Valor unitário");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 60, 76, 14);

        TFValorTotal.setText("");
        jPanel1.add(TFValorTotal);
        TFValorTotal.setBounds(300, 80, 90, 20);

        jLabel6.setText("Valor total");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 60, 76, 14);

        TFUnidade.setEditable(false);
        TFUnidade.setFocusable(false);
        jPanel1.add(TFUnidade);
        TFUnidade.setBounds(10, 80, 100, 20);

        TFQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFQuantidadeFocusLost(evt);
            }
        });
        jPanel1.add(TFQuantidade);
        TFQuantidade.setBounds(120, 80, 80, 20);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search_16.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(90, 30, 20, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 160);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-198)/2, 416, 198);
    }// </editor-fold>//GEN-END:initComponents

    private void BTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalvarActionPerformed
        int ret = 0;
        if (!TFCodProduto.getText().isEmpty()) {
            if (status == 1) {
                SalvaProduto();
            } else if (status == 2) {
                AlteraProduto();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Informe um produto!", "Alerta", JOptionPane.ERROR_MESSAGE);
        }

        frameEntradaProduto.PreencheJtableProdutoEntrada();

}//GEN-LAST:event_BTSalvarActionPerformed

    private void BTSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTSalvarKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            if (!TFProduto.getText().isEmpty()) {
//                if (status == 1) {
//                    SalvaProduto();
//                } else if (status == 2) {
//                    AlteraProduto();
//                }
//            }
//        }
//        FrameComanda.PreencheJtableProduto();
}//GEN-LAST:event_BTSalvarKeyPressed

    private void BTFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFecharActionPerformed
        dispose();
}//GEN-LAST:event_BTFecharActionPerformed

    private void BTFecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTFecharKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
}//GEN-LAST:event_BTFecharKeyPressed

    private void TFCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCodProdutoActionPerformed

    private void TFCodProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFCodProdutoFocusLost
        PegaDescProduto();
    }//GEN-LAST:event_TFCodProdutoFocusLost

    private void TFCodProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCodProdutoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            JTextField tfTextFiel;
            tfTextFiel = TFCodProduto;
            DLInsumos Insumo = new DLInsumos(null, true, tfTextFiel);
            Insumo.setVisible(true);
            PegaDescProduto();
        }
    }//GEN-LAST:event_TFCodProdutoKeyPressed

    private void TFVlrUnitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFVlrUnitarioFocusLost
        CalculaValorTotal();
    }//GEN-LAST:event_TFVlrUnitarioFocusLost

    private void TFQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFQuantidadeFocusLost
        CalculaValorTotal();
    }//GEN-LAST:event_TFQuantidadeFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JTextField tfTextFiel;
        tfTextFiel = TFCodProduto;
        DLInsumos Insumo = new DLInsumos(null, true, tfTextFiel);
        Insumo.setVisible(true);
        PegaDescProduto();
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTFechar;
    private javax.swing.JButton BTSalvar;
    private Componentes.DKJTFInteger TFCodProduto;
    private javax.swing.JTextField TFDescricaoProduto;
    private Componentes.DKJTFFloat3Casas TFQuantidade;
    private javax.swing.JTextField TFUnidade;
    private Componentes.DKJTFFloat TFValorTotal;
    private Componentes.DKJTFFloat TFVlrUnitario;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void SalvaProduto() {
        ResultSet rsEntrada = FMaster.con.executeSQL("select * from estentradas where id_entrada = '" + id_entrada + "'");
        try {
            rsEntrada.first();
            if (rsEntrada.isFirst()) {
                ResultSet rsInsereItemEntrada = FMaster.con.executeSQL("select * from estitementrada where id_itementrada = 0");
                rsInsereItemEntrada.first();
                rsInsereItemEntrada.moveToInsertRow();
                rsInsereItemEntrada.updateInt("id_itementrada", Utilitario.getSequencia("estitementrada", "id_itementrada"));
                rsInsereItemEntrada.updateInt("id_entrada", rsEntrada.getInt("id_entrada"));
                rsInsereItemEntrada.updateInt("id_produto", Integer.parseInt(TFCodProduto.getText().isEmpty() ? "0" : TFCodProduto.getText()));
                rsInsereItemEntrada.updateString("id_unidade", TFUnidade.getText());
                rsInsereItemEntrada.updateFloat("qtde", Float.parseFloat(TFQuantidade.getText().isEmpty() ? "0" : TFQuantidade.getText().replace(",", ".")));
                rsInsereItemEntrada.updateFloat("vlr_unitario", Float.parseFloat(TFVlrUnitario.getText().isEmpty() ? "0" : TFVlrUnitario.getText().replace(",", ".")));
                rsInsereItemEntrada.updateFloat("vlr_total", Float.parseFloat(TFValorTotal.getText().isEmpty() ? "0" : TFValorTotal.getText().replace(",", ".")));
                rsInsereItemEntrada.insertRow();
                LimpaCampos();
            }
        } catch (SQLException ex) {
            Logger.getLogger(DLCadItemEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LimpaCampos() {
        TFCodProduto.setText("");
        TFDescricaoProduto.setText("");
        TFQuantidade.setText("");
        TFVlrUnitario.setText("");
        TFValorTotal.setText("");
        TFUnidade.setText("");
        TFCodProduto.requestFocus();
    }

    private void PegaDescProduto() {
        if (!TFCodProduto.getText().isEmpty()) {
            ResultSet rsproduto = FMaster.con.executeSQL("select * from estproduto where id_produto = '" + TFCodProduto.getText() + "'");
            try {
                rsproduto.first();
                if (rsproduto.isFirst()) {
                    TFDescricaoProduto.setText(rsproduto.getString("descricao"));
                    TFUnidade.setText(rsproduto.getString("unidade_padrao"));
                }
                rsproduto.close();
            } catch (SQLException ex) {
                Logger.getLogger(DLCadItemEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    private void CalculaValorTotal() {
        TFValorTotal.setText(Utilitario.getFomatDecimal(Float.parseFloat(TFQuantidade.getText().isEmpty() ? "0" : TFQuantidade.getText().replace(",", ".")) * Float.parseFloat(TFVlrUnitario.getText().isEmpty() ? "0" : TFVlrUnitario.getText().replace(",", "."))));
    }

    private void PreencheDadosTela() {
        ResultSet rsConsultaProduto = FMaster.con.executeSQL("select * from estitementrada "
                + " inner join estproduto on estitementrada.id_produto = estproduto.id_produto where estitementrada.id_itementrada = '" + id_itementrada + "' and estitementrada.id_entrada = '" + id_entrada + "' and estitementrada.id_produto = '" + id_produto + "'");
        try {
            rsConsultaProduto.first();
            if (rsConsultaProduto.isFirst()) {
                TFCodProduto.setText(rsConsultaProduto.getString("id_produto"));
                TFDescricaoProduto.setText(rsConsultaProduto.getString("descricao"));
                TFQuantidade.setText(Utilitario.getFomatDecimal3Casas(rsConsultaProduto.getFloat("qtde")));
                TFVlrUnitario.setText(Utilitario.getFomatDecimal(rsConsultaProduto.getFloat("vlr_unitario")));
                TFValorTotal.setText(Utilitario.getFomatDecimal(rsConsultaProduto.getFloat("vlr_total")));
                TFUnidade.setText(rsConsultaProduto.getString("id_unidade"));
            }
            rsConsultaProduto.close();

        } catch (SQLException ex) {
            Logger.getLogger(DLCadProdComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void AlteraProduto() {
        ResultSet rsConsultaProduto = FMaster.con.executeSQL("select * from estitementrada where id_itementrada = '" + id_itementrada + "' and id_entrada = '" + id_entrada + "' and id_produto = '" + id_produto + "'");
        try {
            rsConsultaProduto.first();
            if (rsConsultaProduto.isFirst()) {
                rsConsultaProduto.absolute(rsConsultaProduto.getRow());
                rsConsultaProduto.updateInt("id_produto", Integer.parseInt(TFCodProduto.getText().isEmpty() ? "0" : TFCodProduto.getText()));
                rsConsultaProduto.updateString("id_unidade", TFUnidade.getText());
                rsConsultaProduto.updateFloat("qtde", Float.parseFloat(TFQuantidade.getText().isEmpty() ? "0" : TFQuantidade.getText().replace(",", ".")));
                rsConsultaProduto.updateFloat("vlr_unitario", Float.parseFloat(TFVlrUnitario.getText().isEmpty() ? "0" : TFVlrUnitario.getText().replace(",", ".")));
                rsConsultaProduto.updateFloat("vlr_total", Float.parseFloat(TFValorTotal.getText().isEmpty() ? "0" : TFValorTotal.getText().replace(",", ".")));
                rsConsultaProduto.updateRow();
            }
            rsConsultaProduto.close();
            dispose();

        } catch (SQLException ex) {
            Logger.getLogger(DLCadProdComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
