/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DLCadCliComanda.java
 *
 * Created on 10/09/2010, 22:22:01
 */
package Views;

import classess.Utilitario;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Demir
 */
public class DLCadCliComanda extends javax.swing.JDialog {

    String comanda;
    String id_com_clie;
    String id_mesa;
    int status;
    String nomeCliente;
    IFComanda jtableCliente;

    /** Creates new form DLCadCliComanda */
    public DLCadCliComanda(java.awt.Frame parent, boolean modal, String comanda, String id_com_clie, int status, String nomeCliente, String id_mesa, IFComanda jtableCliente) {
        super(parent, modal);
        initComponents();
        //redimenciona o lookandFeeld de acordo com o selecionado
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        this.comanda = comanda;
        this.id_com_clie = id_com_clie;
        this.status = status;
        this.nomeCliente = nomeCliente;
        this.id_mesa = id_mesa;
        this.jtableCliente = jtableCliente;
        if (status == 2) {
            TFNomecliente.setText(nomeCliente);
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFNomecliente = new javax.swing.JTextField();
        BTSalvar = new javax.swing.JButton();
        BTFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastra e Altera clientes da comanda");
        setMinimumSize(new java.awt.Dimension(350, 150));

        jLabel1.setText("Nome Cliente");

        BTSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save_16.png"))); // NOI18N
        BTSalvar.setText("Salvar");
        BTSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTSalvarMouseClicked(evt);
            }
        });
        BTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalvarActionPerformed(evt);
            }
        });
        BTSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BTSalvarKeyPressed(evt);
            }
        });

        BTFechar.setText("Sair");
        BTFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFecharActionPerformed(evt);
            }
        });
        BTFechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BTFecharKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFNomecliente, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTFechar)
                    .addComponent(BTSalvar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-345)/2, (screenSize.height-147)/2, 345, 147);
    }// </editor-fold>//GEN-END:initComponents

    private void BTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalvarActionPerformed
        if (!TFNomecliente.getText().isEmpty()) {
            if (status == 1) {
                SalvaCliente();
            } else if (status == 2) {
                AlteraCliente();
            }
            jtableCliente.PreencherJtableCliente(comanda, id_mesa);
        }
    }//GEN-LAST:event_BTSalvarActionPerformed

    private void BTFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFecharActionPerformed
        dispose();
    }//GEN-LAST:event_BTFecharActionPerformed

    private void BTSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTSalvarMouseClicked
    }//GEN-LAST:event_BTSalvarMouseClicked

    private void BTSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTSalvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (status == 1) {
                SalvaCliente();
            } else if (status == 2) {
                AlteraCliente();
            }
        }
        jtableCliente.PreencherJtableCliente(comanda, id_mesa);
    }//GEN-LAST:event_BTSalvarKeyPressed

    private void BTFecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTFecharKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_BTFecharKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTFechar;
    private javax.swing.JButton BTSalvar;
    private javax.swing.JTextField TFNomecliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void SalvaCliente() {
        ResultSet rsCliComanda = FMaster.con.executeSQL("select * from atncomcli where id_comanda = '" + comanda + "'");
        try {
            rsCliComanda.moveToInsertRow();
            rsCliComanda.updateInt("id_comanda", Integer.parseInt(comanda));
            rsCliComanda.updateInt("id_com_clie", Utilitario.getSequencia("atncomcli", "id_com_clie"));
            rsCliComanda.updateString("nome", TFNomecliente.getText());
            rsCliComanda.updateString("cod_mesa", id_mesa);
            rsCliComanda.insertRow();
            TFNomecliente.setText("");
            TFNomecliente.requestFocus();
            rsCliComanda.close();

        } catch (SQLException ex) {
            Logger.getLogger(DLCadCliComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void AlteraCliente() {
        ResultSet rsCliComanda = FMaster.con.executeSQL("select * from atncomcli where id_comanda = '" + comanda + "' and id_com_clie = '" + id_com_clie + "'");
        try {
            rsCliComanda.first();
            if (rsCliComanda.isFirst()) {
                rsCliComanda.updateString("nome", TFNomecliente.getText());
                rsCliComanda.updateRow();
                dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(DLCadCliComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
