/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DLClienteDelivery.java
 *
 * Created on 06/02/2011, 13:27:57
 */
package Views;

import classess.Utilitario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valdemir
 */
public class DLClienteDelivery extends javax.swing.JDialog {

    String id_cliente = "0";

    /** Creates new form DLClienteDelivery */
    public DLClienteDelivery(java.awt.Frame parent, boolean modal, String telefone) {
        super(parent, modal);
        initComponents();
        //redimenciona o lookandFeeld de acordo com o selecionado
//        SwingUtilities.updateComponentTreeUI(this);
//        this.pack();
        ResultSet rsTelefoneCliente = FMaster.con.executeSQL("select * from dltelefonecliente "
                + "inner join dlcliente on dltelefonecliente.id_cliente = dlcliente.id_cliente where dltelefonecliente.telefone = '" + telefone + "' order by dlcliente.nome");
        DefaultTableModel modelo = (DefaultTableModel) TBCliente.getModel();
        modelo.setNumRows(0);
        try {
            while (rsTelefoneCliente.next()) {
                modelo.addRow(new Object[]{rsTelefoneCliente.getInt("id_cliente"), rsTelefoneCliente.getString("nome"), Utilitario.FormataFone(rsTelefoneCliente.getString("telefone"))});
            }
            rsTelefoneCliente.close();
        } catch (SQLException ex) {
            Logger.getLogger(IFDelivery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Clientes que possui o mesmo telefone");
        getContentPane().setLayout(null);

        TBCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_cliente", "Nome Cliente", "Telecone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBClienteMouseClicked(evt);
            }
        });
        TBCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TBClienteKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TBCliente);
        TBCliente.getColumnModel().getColumn(0).setMinWidth(0);
        TBCliente.getColumnModel().getColumn(0).setPreferredWidth(0);
        TBCliente.getColumnModel().getColumn(0).setMaxWidth(0);
        TBCliente.getColumnModel().getColumn(1).setMinWidth(170);
        TBCliente.getColumnModel().getColumn(1).setPreferredWidth(170);
        TBCliente.getColumnModel().getColumn(1).setMaxWidth(170);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 20, 266, 100);

        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Selecione um cliente usando duplo clique");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 256, 14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-282)/2, (screenSize.height-158)/2, 282, 158);
    }// </editor-fold>//GEN-END:initComponents

    private void TBClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBClienteMouseClicked
        if (evt.getClickCount() > 1) {
            id_cliente = Utilitario.getValueColumn("id_cliente", TBCliente);
            dispose();

        }
    }//GEN-LAST:event_TBClienteMouseClicked

    private void TBClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBClienteKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            id_cliente = Utilitario.getValueColumn("id_cliente", TBCliente);
            dispose();
        }
    }//GEN-LAST:event_TBClienteKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
