/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DLObsItemDelivery.java
 *
 * Created on 04/05/2011, 21:27:43
 */
package Views;

import java.awt.event.KeyEvent;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author stevan t
 */
public class DLObsItemDelivery extends javax.swing.JDialog {
    JTextArea jtfObsItemDelivery;
    /** Creates new form DLObsItemDelivery */
    public DLObsItemDelivery(java.awt.Frame parent, JTextArea jtfObsItemDelivery, int situacacaoDelivery, boolean modal) {
        super(parent, modal);
        initComponents();
        //redimenciona o lookandFeeld de acordo com o selecionado
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        this.jtfObsItemDelivery = jtfObsItemDelivery;
        
        if (this.jtfObsItemDelivery.getText().isEmpty()) {
            TAObservacao.selectAll();
        }
        else {
            TAObservacao.setText(this.jtfObsItemDelivery.getText());
        }
        
        if (situacacaoDelivery>1) {
            TAObservacao.setEditable(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAObservacao = new javax.swing.JTextArea();
        BTOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TAObservacao.setBackground(new java.awt.Color(255, 255, 204));
        TAObservacao.setColumns(20);
        TAObservacao.setLineWrap(true);
        TAObservacao.setRows(5);
        TAObservacao.setText("Observação:");
        TAObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TAObservacaoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TAObservacao);

        BTOk.setText("OK");
        BTOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTOk))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTOk))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-368)/2, (screenSize.height-178)/2, 368, 178);
    }// </editor-fold>//GEN-END:initComponents

    private void BTOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTOkActionPerformed
        jtfObsItemDelivery.setText(TAObservacao.getText());
        this.dispose();
    }//GEN-LAST:event_BTOkActionPerformed

    private void TAObservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TAObservacaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            BTOk.requestFocus();
        }
    }//GEN-LAST:event_TAObservacaoKeyPressed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTOk;
    private javax.swing.JTextArea TAObservacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
