/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FMaster.java
 *
 * Created on 06/09/2010, 21:28:10
 */
package Views;

import classess.Conexao;
import classess.GetsSets;
import classess.ThreadMesas;
import Classes.bematech.BemaECF;
import Properties.Classes.ManipulaPropriedades;
import View_consulta.DLLoginAut;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Demir
 */
public class FMaster extends javax.swing.JFrame {

    Object[] options = {"Sim", "Não"};
    public static Conexao con;

    /** Creates new form FMaster */
    public FMaster() {
        initComponents();

        con = new Conexao();
        con.conecta();
        ThreadMesas tr = new ThreadMesas(jDesktopPane1, jDesktopPane2);

        GetsSets.setJdesktopPanelViews(jDesktopPane2);

        try {
//            UIManager.setLookAndFeel(ManipulaPropriedades.LerAliquota());
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
            // start application
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        LBUsuarioLogado = new javax.swing.JLabel();
        LBUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MIProduto = new javax.swing.JMenuItem();
        MIUsuario = new javax.swing.JMenuItem();
        MIUnidade = new javax.swing.JMenuItem();
        MICliente = new javax.swing.JMenuItem();
        MICaixa = new javax.swing.JMenuItem();
        MIFornecedor = new javax.swing.JMenuItem();
        MIRegiao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISMESA (Sistema para controle de mesas)");
        setBackground(new java.awt.Color(0, 0, 204));
        setForeground(new java.awt.Color(51, 51, 255));

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Descktop.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 910, 690);
        jDesktopPane2.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fac_delivery.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EditComanda.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/People-32.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Caixa.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calculator.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        LBUsuarioLogado.setText("Usuário Logado:");

        LBUsuario.setForeground(new java.awt.Color(0, 51, 255));
        LBUsuario.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(145, 145, 145)
                .addComponent(LBUsuarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBUsuarioLogado)
                        .addComponent(LBUsuario)))
                .addContainerGap())
        );

        jMenu1.setText("Cadastros");

        MIProduto.setText("Produto ");
        MIProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(MIProduto);

        MIUsuario.setText("Usuário");
        MIUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(MIUsuario);

        MIUnidade.setText("Unidade");
        MIUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIUnidadeActionPerformed(evt);
            }
        });
        jMenu1.add(MIUnidade);

        MICliente.setText("Cliente");
        MICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIClienteActionPerformed(evt);
            }
        });
        jMenu1.add(MICliente);

        MICaixa.setText("Caixa");
        MICaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICaixaActionPerformed(evt);
            }
        });
        jMenu1.add(MICaixa);

        MIFornecedor.setText("Fornecedor");
        MIFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(MIFornecedor);

        MIRegiao.setText("Região");
        MIRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIRegiaoActionPerformed(evt);
            }
        });
        jMenu1.add(MIRegiao);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Atendimentos");

        jMenuItem6.setText("Comanda");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem4.setText("Delivery");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Movimentação");

        jMenuItem7.setText("Caixa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem1.setText("Entrada de produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Utilitário");

        jMenu6.setText("Bematech");

        jMenu7.setText("Comandos de Inicialização");

        jMenuItem2.setText("Programação do Horário de Verão");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuItem3.setText("Programação de Aliquota");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenu6.add(jMenu7);

        jMenu8.setText("Comandos do Cupom Fiscal");

        jMenuItem8.setText("Cancela Último Cupom Fiscal");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenu6.add(jMenu8);

        jMenu9.setText("Comandos de Relatórios Fiscais");

        jMenuItem9.setText("Leitura X");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem9);

        jMenuItem10.setText("Redução Z");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem10);

        jMenuItem11.setText("Leitura da Memória Fiscal por Data");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenuItem12.setText("Leitura da Memória Fiscal por Redução");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem12);

        jMenu6.add(jMenu9);

        jMenu5.add(jMenu6);

        jMenuItem13.setText("Visualização Config. Cupom Fiscal");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenu10.setText("Aparência");

        jMenuItem14.setText("Smart");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem14);

        jMenuItem15.setText("Luna");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem15);

        jMenuItem16.setText("Acryl");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem16);

        jMenuItem17.setText("Aero");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem17);

        jMenuItem18.setText("Bernstein");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem18);

        jMenuItem19.setText("Fast");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem19);

        jMenuItem20.setText("Graphite");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem20);

        jMenuItem21.setText("Noire");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed1(evt);
            }
        });
        jMenu10.add(jMenuItem21);

        jMenuItem22.setText("Mint");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem22);

        jMenuItem23.setText("Mcwin");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem23);

        jMenu5.add(jMenu10);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE))
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIProdutoActionPerformed
        if (JIFProduto == null || JIFProduto.isVisible() == false) {
            JIFProduto = new IFProduto();
            jDesktopPane2.add(JIFProduto);
            JIFProduto.setVisible(true);
        }
    }//GEN-LAST:event_MIProdutoActionPerformed

    private void MIUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIUnidadeActionPerformed
        if (JIFUnidade == null || JIFUnidade.isVisible() == false) {
            JIFUnidade = new IFUnidade();
            jDesktopPane2.add(JIFUnidade);
            JIFUnidade.setVisible(true);
        }
    }//GEN-LAST:event_MIUnidadeActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if ((JIFComanda == null || JIFComanda.isVisible() == false) && GetsSets.getJIFComanda() == null) {
            JIFComanda = new IFComanda("");
            jDesktopPane2.add(JIFComanda);
            JIFComanda.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (JIFMovCaixa == null || JIFMovCaixa.isVisible() == false) {
            JIFMovCaixa = new IFMovCaixa();
            jDesktopPane2.add(JIFMovCaixa);
            JIFMovCaixa.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (JIFDelivery == null || JIFDelivery.isVisible() == false) {
            JIFDelivery = new IFDelivery();
            jDesktopPane2.add(JIFDelivery);
            JIFDelivery.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIClienteActionPerformed
        if (JIFCliente == null || JIFCliente.isVisible() == false) {
            JIFCliente = new IFCliente();
            jDesktopPane2.add(JIFCliente);
            JIFCliente.setVisible(true);
        }

    }//GEN-LAST:event_MIClienteActionPerformed

    private void MICaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICaixaActionPerformed
        if (JIFCaixa == null || JIFCaixa.isVisible() == false) {
            JIFCaixa = new IFCaixa();
            jDesktopPane2.add(JIFCaixa);
            JIFCaixa.setVisible(true);
        }
    }//GEN-LAST:event_MICaixaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int iresp = JOptionPane.showOptionDialog(null, "Deseja sair do Sistema?", "", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, //do not use a custom Icon
                options, //the titles of buttons
                options[0]); //default button title
        if (iresp == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (JIFEntradaProduto == null || JIFEntradaProduto.isVisible() == false) {
            JIFEntradaProduto = new IFEntradaProdutos();
            jDesktopPane2.add(JIFEntradaProduto);
            JIFEntradaProduto.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MIUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIUsuarioActionPerformed
        if (JIFUsuario == null || JIFUsuario.isVisible() == false) {
            JIFUsuario = new IFUsuario();
            jDesktopPane2.add(JIFUsuario);
            JIFUsuario.setVisible(true);
        }
    }//GEN-LAST:event_MIUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JIFDelivery == null || JIFDelivery.isVisible() == false) {
            JIFDelivery = new IFDelivery();
            jDesktopPane2.add(JIFDelivery);
            JIFDelivery.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if ((JIFComanda == null || JIFComanda.isVisible() == false) && GetsSets.getJIFComanda() == null) {
            JIFComanda = new IFComanda("");
            jDesktopPane2.add(JIFComanda);
            JIFComanda.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (JIFCliente == null || JIFCliente.isVisible() == false) {
            JIFCliente = new IFCliente();
            jDesktopPane2.add(JIFCliente);
            JIFCliente.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (JIFMovCaixa == null || JIFMovCaixa.isVisible() == false) {
            JIFMovCaixa = new IFMovCaixa();
            jDesktopPane2.add(JIFMovCaixa);
            JIFMovCaixa.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException ex) {
            Logger.getLogger(FMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void MIFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIFornecedorActionPerformed
        if (JIFForecedor == null || JIFForecedor.isVisible() == false) {
            JIFForecedor = new IFFornecedor();
            jDesktopPane2.add(JIFForecedor);
            JIFForecedor.setVisible(true);
        }
    }//GEN-LAST:event_MIFornecedorActionPerformed

    private void MIRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegiaoActionPerformed
        if (JIFRegiao == null || JIFRegiao.isVisible() == false) {
            JIFRegiao = new IFRegiao();
            jDesktopPane2.add(JIFRegiao);
            JIFRegiao.setVisible(true);
        }
    }//GEN-LAST:event_MIRegiaoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        BemaECF.programaHorarioVerao();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        BemaECF.programaAliquota();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        CancelaCupom();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        BemaECF.leituraX();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        BemaECF.leituraZ();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        BemaECF.memoriaFiscalPorData();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        BemaECF.memoriaFiscalPorReducao();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        if (JIFCfgEcf == null || JIFCfgEcf.isVisible() == false) {
            JIFCfgEcf = new IFConfigEc();
            jDesktopPane2.add(JIFCfgEcf);
            JIFCfgEcf.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (JIFEmissorECF == null || JIFEmissorECF.isVisible() == false) {
            JIFEmissorECF = new IFEmiECF();
            jDesktopPane2.add(JIFEmissorECF);
            JIFEmissorECF.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        SetLookAndFeel(1);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        SetLookAndFeel(2);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        SetLookAndFeel(3);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        SetLookAndFeel(4);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        SetLookAndFeel(5);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        SetLookAndFeel(6);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        SetLookAndFeel(7);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        SetLookAndFeel(8);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        SetLookAndFeel(10);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        SetLookAndFeel(9);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem21ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed1
        SetLookAndFeel(8);
    }//GEN-LAST:event_jMenuItem21ActionPerformed1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FMaster().setVisible(true);
                DLLoginAut login = new DLLoginAut(null, true);
                login.setVisible(true);
                if (GetsSets.getCodUser() == 0) {
                    System.exit(0);
                } else {
                    LBUsuario.setText(GetsSets.getNomeUser());
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LBUsuario;
    private javax.swing.JLabel LBUsuarioLogado;
    private javax.swing.JMenuItem MICaixa;
    private javax.swing.JMenuItem MICliente;
    private javax.swing.JMenuItem MIFornecedor;
    private javax.swing.JMenuItem MIProduto;
    private javax.swing.JMenuItem MIRegiao;
    private javax.swing.JMenuItem MIUnidade;
    private javax.swing.JMenuItem MIUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    JInternalFrame JIFProduto;
    JInternalFrame JIFUnidade;
    JInternalFrame JIFComanda;
    JInternalFrame JIFMovCaixa;
    JInternalFrame JIFDelivery;
    JInternalFrame JIFCliente;
    JInternalFrame JIFCaixa;
    JInternalFrame JIFEntradaProduto;
    JInternalFrame JIFUsuario;
    JInternalFrame JIFForecedor;
    JInternalFrame JIFRegiao;
    JInternalFrame JIFCfgEcf;
    JInternalFrame JIFEmissorECF;

    private void CancelaCupom() {
        BemaECF.cancelaCupom();
        if (BemaECF.iRet == 0) {
            ResultSet rsUltimoECF = FMaster.con.executeSQL("select * from atnconfigecf order by idp");
            try {
                rsUltimoECF.last();
                if (rsUltimoECF.isLast()) {

                    ResultSet rsCupomCancelado;
                    rsCupomCancelado = FMaster.con.executeSQL("select * from atncomanda where id_comanda = '" + rsUltimoECF.getInt("id_comanda") + "'");
                    rsCupomCancelado.first();
                    if (rsCupomCancelado.isFirst()) {
                        rsCupomCancelado.updateInt("gerado_cf", 0);
                        rsCupomCancelado.updateRow();
                    }

                    rsCupomCancelado = FMaster.con.executeSQL("select * from dldelivery where id_delivery = '" + rsUltimoECF.getInt("id_delivery") + "'");
                    rsCupomCancelado.first();
                    if (rsCupomCancelado.isFirst()) {
                        rsCupomCancelado.updateInt("gerado_cf", 0);
                        rsCupomCancelado.updateRow();
                    }

                    rsCupomCancelado.close();

                }
                rsUltimoECF.close();
            } catch (SQLException ex) {
                Logger.getLogger(FMaster.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void SetLookAndFeel(int i) {
        try {
            if (i == 1) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.smart.SmartLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
            if (i == 2) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.luna.LunaLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.luna.LunaLookAndFeel");
            }
            if (i == 3) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.acryl.AcrylLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
            if (i == 4) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.aero.AeroLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.aero.AeroLookAndFeel");
            }
            if (i == 5) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.bernstein.BernsteinLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
            }
            if (i == 6) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.fast.FastLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.fast.FastLookAndFeel");
            }
            if (i == 7) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
            }
            if (i == 8) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.noire.NoireLookAndFeel");
            }
            if (i == 9) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.mint.MintLookAndFeel");
            }
            if (i == 10) {
//                UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
//                SwingUtilities.updateComponentTreeUI(this);
//                this.pack();
                //this.setExtendedState(this.MAXIMIZED_BOTH);
                ManipulaPropriedades.gravaAliquota("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            }

            JOptionPane.showMessageDialog(null, "O sistema deve ser reiniciado para obter a nova aparência!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
