/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IFCliente.java
 *
 * Created on 22/10/2010, 15:05:58
 */
package Views;

import classess.CepWebService;
import classess.Utilitario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author DK
 */
public class IFFornecedor extends javax.swing.JInternalFrame {

    Object[] options = {"Sim", "Não"};

    public IFFornecedor() {
        initComponents();
        //redimenciona o lookandFeeld de acordo com o selecionado
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        PreencherJtableConsulta();
        TFNome.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAObs = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        TFcodCli = new javax.swing.JTextField();
        TFNome = new javax.swing.JTextField();
        TFCNPJ = new javax.swing.JTextField();
        TFBairro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TFNumero = new Componentes.DKJTFInteger();
        jLabel15 = new javax.swing.JLabel();
        TFCep1 = new Componentes.DKJTFCep();
        TFCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CBEstado = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        BTNovo = new javax.swing.JButton();
        BTSalvar = new javax.swing.JButton();
        BTExcluir = new javax.swing.JButton();
        TFRua = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TFCPF = new Componentes.DKJTFCpf();
        TFTelefone02 = new Componentes.DKJTFFone();
        jLabel17 = new javax.swing.JLabel();
        TFTelefone01 = new Componentes.DKJTFFone();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        FTFfiltro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TFDESCGERAL = new javax.swing.JTextField();
        BT_FILTER = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbPadrao = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de fornecedor");
        setMinimumSize(new java.awt.Dimension(605, 372));
        setRequestFocusEnabled(false);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setLayout(null);

        jLabel1.setText("Código");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 10, 50, 14);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(6, 167, 0, 0);

        jLabel2.setText("Nome");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(60, 10, 170, 14);

        jLabel4.setText("Rua");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(430, 60, 40, 14);

        jLabel6.setText("Bairro");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(290, 60, 70, 14);

        jLabel7.setText("Número");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(550, 60, 50, 14);

        TAObs.setColumns(20);
        TAObs.setRows(5);
        TAObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TAObsKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TAObs);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 130, 630, 140);

        jLabel8.setText("Observação");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 110, 130, 14);

        TFcodCli.setBackground(new java.awt.Color(204, 204, 204));
        TFcodCli.setEditable(false);
        TFcodCli.setEnabled(false);
        TFcodCli.setFocusable(false);
        jPanel3.add(TFcodCli);
        TFcodCli.setBounds(10, 30, 40, 20);

        TFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNomeActionPerformed(evt);
            }
        });
        jPanel3.add(TFNome);
        TFNome.setBounds(60, 30, 170, 20);
        jPanel3.add(TFCNPJ);
        TFCNPJ.setBounds(550, 30, 90, 20);

        TFBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBairroActionPerformed(evt);
            }
        });
        jPanel3.add(TFBairro);
        TFBairro.setBounds(290, 80, 130, 20);

        jLabel14.setText("Cep");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 60, 50, 14);

        TFNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNumeroActionPerformed(evt);
            }
        });
        jPanel3.add(TFNumero);
        TFNumero.setBounds(550, 80, 90, 20);

        jLabel15.setText("CNPJ");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(550, 10, 50, 14);

        TFCep1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFCep1FocusLost(evt);
            }
        });
        jPanel3.add(TFCep1);
        TFCep1.setBounds(10, 80, 80, 20);
        jPanel3.add(TFCidade);
        TFCidade.setBounds(100, 80, 110, 20);

        jLabel9.setText("Estado");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(220, 60, 50, 14);

        CBEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        CBEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(CBEstado);
        CBEstado.setBounds(220, 80, 60, 20);

        jLabel10.setText("Cidade");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(110, 60, 90, 14);

        BTNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clear-32.png"))); // NOI18N
        BTNovo.setText("Limpar"); // NOI18N
        BTNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNovoActionPerformed(evt);
            }
        });
        jPanel3.add(BTNovo);
        BTNovo.setBounds(350, 280, 99, 30);

        BTSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1287691458_thumb-up.png"))); // NOI18N
        BTSalvar.setText("Salvar"); // NOI18N
        BTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalvarActionPerformed(evt);
            }
        });
        jPanel3.add(BTSalvar);
        BTSalvar.setBounds(460, 280, 91, 30);

        BTExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_16.png"))); // NOI18N
        BTExcluir.setText("Excluir"); // NOI18N
        BTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(BTExcluir);
        BTExcluir.setBounds(560, 280, 83, 30);
        jPanel3.add(TFRua);
        TFRua.setBounds(430, 80, 110, 20);

        jLabel16.setText("Telefone02");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(350, 10, 90, 14);

        TFCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCPFActionPerformed(evt);
            }
        });
        jPanel3.add(TFCPF);
        TFCPF.setBounds(450, 30, 90, 20);
        jPanel3.add(TFTelefone02);
        TFTelefone02.setBounds(350, 30, 90, 20);

        jLabel17.setText("CPF");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(460, 10, 50, 14);
        jPanel3.add(TFTelefone01);
        TFTelefone01.setBounds(250, 30, 90, 20);

        jLabel18.setText("Telefone01");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(250, 10, 90, 14);

        jTabbedPane1.addTab("Cadastro", jPanel3);

        FTFfiltro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Nome do cliente:"); // NOI18N

        TFDESCGERAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFDESCGERALKeyReleased(evt);
            }
        });

        BT_FILTER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clear-32.png"))); // NOI18N
        BT_FILTER.setText("Limpar"); // NOI18N
        BT_FILTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_FILTERActionPerformed(evt);
            }
        });
        BT_FILTER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BT_FILTERKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout FTFfiltroLayout = new javax.swing.GroupLayout(FTFfiltro);
        FTFfiltro.setLayout(FTFfiltroLayout);
        FTFfiltroLayout.setHorizontalGroup(
            FTFfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTFfiltroLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFDESCGERAL, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(BT_FILTER, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FTFfiltroLayout.setVerticalGroup(
            FTFfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTFfiltroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(FTFfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TFDESCGERAL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(BT_FILTER)
        );

        TbPadrao.setAutoCreateRowSorter(true);
        TbPadrao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TbPadrao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Telefone01", "Telefone02", "Rua", "Numero", "Bairro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbPadrao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbPadraoMouseClicked1(evt);
            }
        });
        TbPadrao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TbPadraoKeyPressed1(evt);
            }
        });
        jScrollPane3.setViewportView(TbPadrao);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FTFfiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FTFfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pesquisa", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(100, 50, 671, 372);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNovoActionPerformed
        LimpaCampos();
}//GEN-LAST:event_BTNovoActionPerformed

    private void BTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalvarActionPerformed
        if (CBEstado.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Informe o estado!", "Alerta", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (TFcodCli.getText().isEmpty()) {
            SalvarFornecedor();
        } else {
            AlterarFornecedor();
        }
}//GEN-LAST:event_BTSalvarActionPerformed

    private void BTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTExcluirActionPerformed
        DeletaCliente();
}//GEN-LAST:event_BTExcluirActionPerformed

    private void TFDESCGERALKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDESCGERALKeyReleased
        PreencherJtableConsulta();
}//GEN-LAST:event_TFDESCGERALKeyReleased

    private void BT_FILTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_FILTERActionPerformed
        LimpaCamposSelecao();
        PreencherJtableConsulta();
}//GEN-LAST:event_BT_FILTERActionPerformed

    private void BT_FILTERKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BT_FILTERKeyPressed
//        if (evt.getKeyCode() == evt.VK_ENTER) {
//            LimpaCamposSelecao();
//            Filtra();
//        }
}//GEN-LAST:event_BT_FILTERKeyPressed

    private void TbPadraoMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbPadraoMouseClicked1
        if (evt.getClickCount() > 1) {
            posicionaFornecedor();
        }
}//GEN-LAST:event_TbPadraoMouseClicked1

    private void TbPadraoKeyPressed1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TbPadraoKeyPressed1
        if (evt.getKeyCode() == evt.VK_ENTER) {
            posicionaFornecedor();

        }
}//GEN-LAST:event_TbPadraoKeyPressed1

    private void TFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNomeActionPerformed

    private void TFBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBairroActionPerformed

    private void TFNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNumeroActionPerformed

    private void TFCep1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFCep1FocusLost
//        GetCepWeb();
    }//GEN-LAST:event_TFCep1FocusLost

    private void CBEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEstadoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CBEstadoActionPerformed

    private void TAObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TAObsKeyPressed
        if (evt.getKeyCode() == evt.VK_TAB) {
            BTSalvar.requestFocus();
        }
    }//GEN-LAST:event_TAObsKeyPressed

    private void TFCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCPFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTExcluir;
    private javax.swing.JButton BTNovo;
    private javax.swing.JButton BTSalvar;
    private javax.swing.JButton BT_FILTER;
    private javax.swing.JComboBox CBEstado;
    private javax.swing.JPanel FTFfiltro;
    private javax.swing.JTextArea TAObs;
    private javax.swing.JTextField TFBairro;
    private javax.swing.JTextField TFCNPJ;
    private Componentes.DKJTFCpf TFCPF;
    private Componentes.DKJTFCep TFCep1;
    private javax.swing.JTextField TFCidade;
    private javax.swing.JTextField TFDESCGERAL;
    private javax.swing.JTextField TFNome;
    private Componentes.DKJTFInteger TFNumero;
    private javax.swing.JTextField TFRua;
    private Componentes.DKJTFFone TFTelefone01;
    private Componentes.DKJTFFone TFTelefone02;
    private javax.swing.JTextField TFcodCli;
    private javax.swing.JTable TbPadrao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void SalvarFornecedor() {
        ResultSet rsFornecedor = FMaster.con.executeSQL("select * from estfornecedor where id_fornecedor = 0");
        try {
            rsFornecedor.first();
            rsFornecedor.moveToInsertRow();
            rsFornecedor.updateInt("id_fornecedor", Utilitario.getSequencia("estfornecedor", "id_fornecedor"));
            rsFornecedor.updateString("nome", TFNome.getText());
            rsFornecedor.updateString("cpf", TFCPF.getText().replace(".", "").replace("-", ""));
            rsFornecedor.updateString("cnpj", TFCNPJ.getText().replace(".", "").replace("-", ""));
            rsFornecedor.updateString("cep", TFCep1.getText().replace(".", "").replace("-", ""));
            rsFornecedor.updateString("cidade", TFCidade.getText());
            rsFornecedor.updateString("uf", CBEstado.getSelectedItem().toString());
            rsFornecedor.updateString("bairro", TFBairro.getText());
            rsFornecedor.updateString("rua", TFCNPJ.getText());
            rsFornecedor.updateInt("numero", Integer.parseInt(TFNumero.getText().isEmpty() ? "0" : TFNumero.getText()));
            rsFornecedor.updateString("obs", TAObs.getText());
            rsFornecedor.updateString("telefone1", TFTelefone01.getText().isEmpty()?"":TFTelefone01.getText().replace("(", "").replace(")", "").replace("-", ""));
            rsFornecedor.updateString("telefone2", TFTelefone02.getText().isEmpty()?"":TFTelefone02.getText().replace("(", "").replace(")", "").replace("-", ""));
            rsFornecedor.insertRow();
            prencherHeder(rsFornecedor.getInt("id_fornecedor"));
            rsFornecedor.close();
            PreencherJtableConsulta();
        } catch (SQLException ex) {
            Logger.getLogger(IFFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void AlterarFornecedor() {
        ResultSet rsFornecedor = FMaster.con.executeSQL("select * from estfornecedor where id_fornecedor  = '" + TFcodCli.getText() + "'");
        try {
            rsFornecedor.first();
            if (rsFornecedor.isFirst()) {
                int iresp = JOptionPane.showOptionDialog(null, "Deseja alterar?", "", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null, //do not use a custom Icon
                        options, //the titles of buttons
                        options[0]); //default button title
                if (iresp == 0) {

                    rsFornecedor.absolute(rsFornecedor.getRow());
                    rsFornecedor.updateString("nome", TFNome.getText());
                    rsFornecedor.updateString("cpf", TFCPF.getText().replace(".", "").replace("-", ""));
                    rsFornecedor.updateString("cnpj", TFCNPJ.getText().replace(".", "").replace("-", ""));
                    rsFornecedor.updateString("cep", TFCep1.getText().replace(".", "").replace("-", ""));
                    rsFornecedor.updateString("cidade", TFCidade.getText());
                    rsFornecedor.updateString("uf", CBEstado.getSelectedItem().toString());
                    rsFornecedor.updateString("bairro", TFBairro.getText());
                    rsFornecedor.updateString("rua", TFCNPJ.getText());
                    rsFornecedor.updateInt("numero", Integer.parseInt(TFNumero.getText().isEmpty() ? "0" : TFNumero.getText()));
                    rsFornecedor.updateString("obs", TAObs.getText());
                    rsFornecedor.updateString("telefone1", TFTelefone01.getText().isEmpty()?"":TFTelefone01.getText().replace("(", "").replace(")", "").replace("-", ""));
                    rsFornecedor.updateString("telefone2", TFTelefone02.getText().isEmpty()?"":TFTelefone02.getText().replace("(", "").replace(")", "").replace("-", ""));
                    rsFornecedor.updateRow();
                    prencherHeder(rsFornecedor.getInt("id_fornecedor"));
                    PreencherJtableConsulta();
                }
            }
            rsFornecedor.close();
        } catch (SQLException ex) {
            Logger.getLogger(IFProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void prencherHeder(int aInt) {
        ResultSet rsFornecedor = FMaster.con.executeSQL("select * from estfornecedor where id_fornecedor = '" + aInt + "'");
        try {
            rsFornecedor.first();
            if (rsFornecedor.isFirst()) {
                TFcodCli.setText(rsFornecedor.getString("id_fornecedor"));
                TFNome.setText(rsFornecedor.getString("nome"));
                TFCNPJ.setText(rsFornecedor.getString("rua"));
                TFCidade.setText(rsFornecedor.getString("cidade"));
                CBEstado.setSelectedItem(rsFornecedor.getString("uf"));
                TFNumero.setText(rsFornecedor.getString("numero"));
                TFBairro.setText(rsFornecedor.getString("bairro"));
                TFCep1.setText(rsFornecedor.getString("cep"));
                TFCPF.setText(rsFornecedor.getString("cpf"));
                TFCNPJ.setText(rsFornecedor.getString("cnpj"));
                TAObs.setText(rsFornecedor.getString("obs"));
                TFTelefone01.setText(rsFornecedor.getString("telefone1"));
                TFTelefone02.setText(rsFornecedor.getString("telefone2"));
            }
            rsFornecedor.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema no posicionamento do forncedor");
        }
    }



    private void LimpaCampos() {
        TFcodCli.setText("");
        TFNome.setText("");
        TFCNPJ.setText("");
        TFNumero.setText("");
        TFBairro.setText("");
        TFCep1.setText("");
        TAObs.setText("");
        TFCPF.setText("");
        TFCNPJ.setText("");
        TFCidade.setText("");
        TFTelefone01.setText("");
        TFTelefone02.setText("");
    }

    private void DeletaCliente() {

        //
        if (!TFcodCli.getText().isEmpty()) {
            String id_fornecedor = TFcodCli.getText().isEmpty() ? "0" : TFcodCli.getText();
            ResultSet rsFornecedor = FMaster.con.executeSQL("select * from estfornecedor where id_fornecedor = '" + id_fornecedor + "'");
            try {
                rsFornecedor.first();
                if (rsFornecedor.isFirst()) {
                    rsFornecedor.absolute(rsFornecedor.getRow());
                    rsFornecedor.deleteRow();
                    LimpaCampos();
                    PreencherJtableConsulta();
                } else {
                    JOptionPane.showMessageDialog(null, "Um forncedor deve ser informada!", "Alerta", JOptionPane.ERROR_MESSAGE);
                }
                rsFornecedor.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o o fornecedor!", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void PreencherJtableConsulta() {
        ResultSet rsCliente = FMaster.con.executeSQL("select * from estfornecedor " + Filtra() + " order by id_fornecedor");
        DefaultTableModel modelo = (DefaultTableModel) TbPadrao.getModel();
        modelo.setNumRows(0);
        try {
            while (rsCliente.next()) {
                modelo.addRow(new Object[]{rsCliente.getInt("id_fornecedor"), rsCliente.getString("nome"), Utilitario.FormataFone(rsCliente.getString("telefone1")),Utilitario.FormataFone(rsCliente.getString("telefone2")),rsCliente.getString("rua"), rsCliente.getInt("numero"), rsCliente.getString("bairro")});
            }
            rsCliente.close();
        } catch (SQLException ex) {
            Logger.getLogger(IFProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String Filtra() {

        String descricao = TFDESCGERAL.getText().isEmpty() ? "" : TFDESCGERAL.getText();
        String filtro = "";
        if (!descricao.equals("")) {
            if (filtro.equals("")) {
                filtro = " where Upper(nome) like '%" + descricao.toUpperCase() + "%'";
            } else {
                filtro = filtro + " and Upper(nome) like '%" + descricao.toUpperCase() + "%'";
            }
        }
        return filtro;
    }

    private void posicionaFornecedor() {
        String id_fornecedor = Utilitario.getValueColumn("Código", TbPadrao);
        prencherHeder(Integer.parseInt(id_fornecedor));
        jTabbedPane1.setSelectedIndex(0);
    }

    private void LimpaCamposSelecao() {
        TFDESCGERAL.setText("");
    }

    private void GetCepWeb() {
        if (TFCNPJ.getText().isEmpty() && TFBairro.getText().isEmpty() && TFCidade.getText().isEmpty()) {
            String cep = TFCep1.getText().replace(".", "").replace("-", "");
            CepWebService cepWebService = new CepWebService(cep);
            if (TFCNPJ.getText().isEmpty() && !cepWebService.getTipo_logradouro().isEmpty()) {
                TFCNPJ.setText(cepWebService.getTipo_logradouro() + " " + cepWebService.getLogradouro());
            }
            if (TFBairro.getText().isEmpty()) {
                TFBairro.setText(cepWebService.getBairro());
            }
            if (TFCidade.getText().isEmpty()) {
                TFCidade.setText(cepWebService.getCidade());
            }
            String uf = cepWebService.getEstado();
            System.out.println(uf);
            CBEstado.setSelectedItem(uf);

        }
    }
}
